version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 99
  assignees:
  - keenwon
  versioning-strategy: increase
  ignore:
  - dependency-name: elint
    versions:
    - "> 2.0.0.pre.alpha.3, < 3"
  - dependency-name: mocha
    versions:
    - ">= 8.a, < 9"
