# 启用的插件
enable:
  - google
  - youdao
  - bing

# 缓存的时间
#   年: y
#   月: M
#   周: w
#   天: d
expires: '2M'

# 彩色输出
colorful: true

# 插件设置（插件支持该项设置才有效）
plugins:
  youdao:
    retries: 2        # 重试次数
    timeout: 5000     # 超时时间 单位毫秒
    proxy: false      # 代理设置 关闭: false, 开启: socks://127.0.0.1:1080 (或https)
    output:
      examples: 2     # 是否显示例句 不显示：0, 不限: -1, 其他为设置具体条数
      phonetics: -1   # 是否显示音标
      translates: 4  # 是否显示翻译

  google:
    retries: 2
    timeout: 5000
    proxy: false
    output:
      examples: 2
      phonetics: -1
      translates: 4

  bing:
    retries: 2
    timeout: 5000
    proxy: false
    output:
      examples: 2
      phonetics: -1
      translates: 4
