name: unittest

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14, 18]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: 'x64'

      - name: npm install
        run: npm install

      - name: npm run test
        run: npm run test

      - name: npm run test:coverage
        if: matrix.node_version == 16 && matrix.os == 'ubuntu-latest'
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        if: matrix.node_version == 16 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
